[package]
name = "grant"
version = "0.1.0"
edition = "2021"
authors = ["Duyet Le <me@duyet.net>"]
license = "MIT"
description = "A tool to search files"
readme = "README.md"


[dependencies]
structopt = "0.3.13"
anyhow = "1.0"
yaml-rust = "0.4"
yaml-validator = "0.1"
indoc = "1.0"
log = "0.4"
env_logger = "0.9"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
tempfile = "3"
